yaml:
  name: application.yml
  aliases:
    - properties.yml
    - env.yml

server:
  port: 8080
  servlet:
    session:
      timeout: 1800

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/library_sandbox
    username: root
#    password:
  session:
    jdbc:
      initialize-schema: always